# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFormLayout, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLCDNumber, QLabel,
    QListView, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QSpacerItem, QStatusBar, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1268, 806)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalWidget = QWidget(self.centralwidget)
        self.horizontalWidget.setObjectName(u"horizontalWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy1)
        self.gridLayout_3 = QGridLayout(self.horizontalWidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.horizontalFrame = QFrame(self.horizontalWidget)
        self.horizontalFrame.setObjectName(u"horizontalFrame")
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer = QSpacerItem(50, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.label_2 = QLabel(self.horizontalFrame)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QSize(60, 60))
        self.label_2.setTextFormat(Qt.TextFormat.AutoText)
        self.label_2.setPixmap(QPixmap(u"images.jpeg"))
        self.label_2.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label_6 = QLabel(self.horizontalFrame)
        self.label_6.setObjectName(u"label_6")
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(2, 82, 182, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        brush2 = QBrush(QColor(127, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        brush3 = QBrush(QColor(170, 170, 170, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush4)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        brush5 = QBrush(QColor(255, 255, 220, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush4)
        brush6 = QBrush(QColor(0, 0, 0, 127))
        brush6.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush6)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush4)
        brush7 = QBrush(QColor(127, 127, 127, 127))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.label_6.setPalette(palette)
        font1 = QFont()
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setUnderline(False)
        self.label_6.setFont(font1)
        self.label_6.setAutoFillBackground(True)

        self.horizontalLayout_2.addWidget(self.label_6)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)


        self.gridLayout_3.addWidget(self.horizontalFrame, 0, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.horizontalWidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy2)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        self.groupBox_3.setPalette(palette1)
        font2 = QFont()
        font2.setPointSize(15)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setKerning(True)
        font2.setHintingPreference(QFont.PreferDefaultHinting)
        self.groupBox_3.setFont(font2)
        self.groupBox_3.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.groupBox_3.setFlat(False)
        self._2 = QVBoxLayout(self.groupBox_3)
        self._2.setObjectName(u"_2")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_display = QLabel(self.groupBox_3)
        self.label_display.setObjectName(u"label_display")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(2)
        sizePolicy3.setVerticalStretch(2)
        sizePolicy3.setHeightForWidth(self.label_display.sizePolicy().hasHeightForWidth())
        self.label_display.setSizePolicy(sizePolicy3)

        self.verticalLayout_3.addWidget(self.label_display)

        self.widget_2 = QWidget(self.groupBox_3)
        self.widget_2.setObjectName(u"widget_2")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy4)
        self.horizontalLayout = QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalFrame = QFrame(self.widget_2)
        self.verticalFrame.setObjectName(u"verticalFrame")
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalLayout_5 = QVBoxLayout(self.verticalFrame)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.radioButton_video_mode = QRadioButton(self.verticalFrame)
        self.radioButton_video_mode.setObjectName(u"radioButton_video_mode")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.radioButton_video_mode.sizePolicy().hasHeightForWidth())
        self.radioButton_video_mode.setSizePolicy(sizePolicy5)
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setKerning(True)
        font3.setHintingPreference(QFont.PreferDefaultHinting)
        self.radioButton_video_mode.setFont(font3)
        self.radioButton_video_mode.setChecked(True)

        self.verticalLayout_5.addWidget(self.radioButton_video_mode)

        self.radioButton_image_mode = QRadioButton(self.verticalFrame)
        self.radioButton_image_mode.setObjectName(u"radioButton_image_mode")
        sizePolicy5.setHeightForWidth(self.radioButton_image_mode.sizePolicy().hasHeightForWidth())
        self.radioButton_image_mode.setSizePolicy(sizePolicy5)
        self.radioButton_image_mode.setFont(font3)

        self.verticalLayout_5.addWidget(self.radioButton_image_mode)


        self.horizontalLayout.addWidget(self.verticalFrame)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)

        self.verticalWidget = QWidget(self.widget_2)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.verticalLayout_4 = QVBoxLayout(self.verticalWidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.radioButton_preview = QRadioButton(self.verticalWidget)
        self.radioButton_preview.setObjectName(u"radioButton_preview")
        self.radioButton_preview.setFont(font3)
        self.radioButton_preview.setChecked(True)

        self.verticalLayout_4.addWidget(self.radioButton_preview)

        self.radioButton_autodetect = QRadioButton(self.verticalWidget)
        self.radioButton_autodetect.setObjectName(u"radioButton_autodetect")
        self.radioButton_autodetect.setFont(font3)

        self.verticalLayout_4.addWidget(self.radioButton_autodetect)


        self.horizontalLayout.addWidget(self.verticalWidget)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.formFrame = QFrame(self.widget_2)
        self.formFrame.setObjectName(u"formFrame")
        sizePolicy4.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy4)
        self.gridLayout_4 = QGridLayout(self.formFrame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.pushButton_Resume = QPushButton(self.formFrame)
        self.pushButton_Resume.setObjectName(u"pushButton_Resume")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.pushButton_Resume.sizePolicy().hasHeightForWidth())
        self.pushButton_Resume.setSizePolicy(sizePolicy6)
        self.pushButton_Resume.setMinimumSize(QSize(180, 0))
        self.pushButton_Resume.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_Resume, 1, 0, 1, 1)

        self.pushButton_select_file = QPushButton(self.formFrame)
        self.pushButton_select_file.setObjectName(u"pushButton_select_file")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.pushButton_select_file.sizePolicy().hasHeightForWidth())
        self.pushButton_select_file.setSizePolicy(sizePolicy7)
        self.pushButton_select_file.setMinimumSize(QSize(180, 0))
        self.pushButton_select_file.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_select_file, 1, 1, 1, 1)

        self.pushButton_stop = QPushButton(self.formFrame)
        self.pushButton_stop.setObjectName(u"pushButton_stop")
        sizePolicy6.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy6)
        self.pushButton_stop.setMinimumSize(QSize(180, 0))
        self.pushButton_stop.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_stop, 3, 0, 1, 1)

        self.pushButton_reformat = QPushButton(self.formFrame)
        self.pushButton_reformat.setObjectName(u"pushButton_reformat")
        self.pushButton_reformat.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_reformat, 3, 1, 1, 1)

        self.pushButton_4 = QPushButton(self.formFrame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy7.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy7)
        self.pushButton_4.setMinimumSize(QSize(180, 0))
        self.pushButton_4.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_4, 4, 1, 1, 1)

        self.pushButton_Detect = QPushButton(self.formFrame)
        self.pushButton_Detect.setObjectName(u"pushButton_Detect")
        self.pushButton_Detect.setFont(font3)

        self.gridLayout_4.addWidget(self.pushButton_Detect, 4, 0, 1, 1)


        self.horizontalLayout.addWidget(self.formFrame)


        self.verticalLayout_3.addWidget(self.widget_2)


        self._2.addLayout(self.verticalLayout_3)


        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.groupBox = QGroupBox(self.horizontalWidget)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy8.setHorizontalStretch(1)
        sizePolicy8.setVerticalStretch(1)
        sizePolicy8.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy8)
        font4 = QFont()
        font4.setPointSize(15)
        font4.setBold(False)
        font4.setUnderline(False)
        font4.setKerning(True)
        self.groupBox.setFont(font4)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy9)
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(False)
        font5.setUnderline(True)
        font5.setStrikeOut(False)
        font5.setKerning(True)
        self.label_7.setFont(font5)

        self.verticalLayout_2.addWidget(self.label_7)

        self.widget = QWidget(self.groupBox)
        self.widget.setObjectName(u"widget")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy10)
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.listView = QListView(self.widget)
        self.listView.setObjectName(u"listView")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy11)
        self.listView.setMinimumSize(QSize(250, 100))
        self.listView.setMaximumSize(QSize(600, 600))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        self.listView.setPalette(palette2)
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(False)
        font6.setItalic(False)
        font6.setUnderline(True)
        font6.setKerning(True)
        font6.setHintingPreference(QFont.PreferDefaultHinting)
        self.listView.setFont(font6)

        self.verticalLayout.addWidget(self.listView)


        self.verticalLayout_2.addWidget(self.widget)

        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        sizePolicy9.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy9)
        self.label_8.setFont(font5)

        self.verticalLayout_2.addWidget(self.label_8)

        self.horizontalWidget1 = QWidget(self.groupBox)
        self.horizontalWidget1.setObjectName(u"horizontalWidget1")
        sizePolicy9.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy9)
        self.formLayout = QFormLayout(self.horizontalWidget1)
        self.formLayout.setObjectName(u"formLayout")
        self.widget1 = QWidget(self.horizontalWidget1)
        self.widget1.setObjectName(u"widget1")
        self.gridLayout_2 = QGridLayout(self.widget1)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.lcdNumber_landslide = QLCDNumber(self.widget1)
        self.lcdNumber_landslide.setObjectName(u"lcdNumber_landslide")
        self.lcdNumber_landslide.setMinimumSize(QSize(80, 0))
        self.lcdNumber_landslide.setMaximumSize(QSize(50, 20))
        font7 = QFont()
        font7.setFamilies([u"Ubuntu"])
        font7.setPointSize(20)
        font7.setBold(True)
        font7.setItalic(False)
        font7.setUnderline(True)
        font7.setKerning(True)
        self.lcdNumber_landslide.setFont(font7)
#if QT_CONFIG(accessibility)
        self.lcdNumber_landslide.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcdNumber_landslide.setAutoFillBackground(True)
        self.lcdNumber_landslide.setFrameShadow(QFrame.Shadow.Plain)
        self.lcdNumber_landslide.setLineWidth(1)
        self.lcdNumber_landslide.setMidLineWidth(1)
        self.lcdNumber_landslide.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)

        self.gridLayout_2.addWidget(self.lcdNumber_landslide, 3, 1, 1, 1)

        self.lcdNumber_stone = QLCDNumber(self.widget1)
        self.lcdNumber_stone.setObjectName(u"lcdNumber_stone")
        self.lcdNumber_stone.setMinimumSize(QSize(80, 0))
        self.lcdNumber_stone.setMaximumSize(QSize(50, 20))
        self.lcdNumber_stone.setFont(font7)
#if QT_CONFIG(accessibility)
        self.lcdNumber_stone.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcdNumber_stone.setAutoFillBackground(True)
        self.lcdNumber_stone.setStyleSheet(u"font: 700 20pt \"Ubuntu\";")
        self.lcdNumber_stone.setFrameShadow(QFrame.Shadow.Plain)
        self.lcdNumber_stone.setLineWidth(1)
        self.lcdNumber_stone.setMidLineWidth(1)
        self.lcdNumber_stone.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)

        self.gridLayout_2.addWidget(self.lcdNumber_stone, 0, 1, 1, 1)

        self.lcdNumber_fallentree = QLCDNumber(self.widget1)
        self.lcdNumber_fallentree.setObjectName(u"lcdNumber_fallentree")
        self.lcdNumber_fallentree.setMinimumSize(QSize(80, 0))
        self.lcdNumber_fallentree.setMaximumSize(QSize(50, 20))
        self.lcdNumber_fallentree.setFont(font7)
#if QT_CONFIG(accessibility)
        self.lcdNumber_fallentree.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcdNumber_fallentree.setAutoFillBackground(True)
        self.lcdNumber_fallentree.setFrameShadow(QFrame.Shadow.Plain)
        self.lcdNumber_fallentree.setLineWidth(1)
        self.lcdNumber_fallentree.setMidLineWidth(1)
        self.lcdNumber_fallentree.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)

        self.gridLayout_2.addWidget(self.lcdNumber_fallentree, 1, 1, 1, 1)

        self.label = QLabel(self.widget1)
        self.label.setObjectName(u"label")
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(False)
        font8.setUnderline(False)
        font8.setKerning(True)
        self.label.setFont(font8)

        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)

        self.label_3 = QLabel(self.widget1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font8)

        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)

        self.label_5 = QLabel(self.widget1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFont(font8)

        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)

        self.lcdNumber_roadcollapse = QLCDNumber(self.widget1)
        self.lcdNumber_roadcollapse.setObjectName(u"lcdNumber_roadcollapse")
        self.lcdNumber_roadcollapse.setMinimumSize(QSize(80, 0))
        self.lcdNumber_roadcollapse.setMaximumSize(QSize(50, 20))
        self.lcdNumber_roadcollapse.setFont(font7)
#if QT_CONFIG(accessibility)
        self.lcdNumber_roadcollapse.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcdNumber_roadcollapse.setAutoFillBackground(True)
        self.lcdNumber_roadcollapse.setFrameShadow(QFrame.Shadow.Plain)
        self.lcdNumber_roadcollapse.setLineWidth(1)
        self.lcdNumber_roadcollapse.setMidLineWidth(1)
        self.lcdNumber_roadcollapse.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)

        self.gridLayout_2.addWidget(self.lcdNumber_roadcollapse, 2, 1, 1, 1)

        self.label_4 = QLabel(self.widget1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font8)

        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)


        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.widget1)


        self.verticalLayout_2.addWidget(self.horizontalWidget1)


        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 1)


        self.gridLayout.addWidget(self.horizontalWidget, 0, 1, 3, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("")
        self.label_2.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Traffic Disaster Detection Platform", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Display", None))
        self.label_display.setText("")
        self.radioButton_video_mode.setText(QCoreApplication.translate("MainWindow", u"Video", None))
        self.radioButton_image_mode.setText(QCoreApplication.translate("MainWindow", u"Figure", None))
        self.radioButton_preview.setText(QCoreApplication.translate("MainWindow", u"Preview", None))
        self.radioButton_autodetect.setText(QCoreApplication.translate("MainWindow", u"Auto-Detect", None))
        self.pushButton_Resume.setText(QCoreApplication.translate("MainWindow", u"Resume", None))
        self.pushButton_select_file.setText(QCoreApplication.translate("MainWindow", u"Choose Directory", None))
        self.pushButton_stop.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.pushButton_reformat.setText(QCoreApplication.translate("MainWindow", u"Format Filename", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Save Data", None))
        self.pushButton_Detect.setText(QCoreApplication.translate("MainWindow", u"Detect", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Statistics", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Filename", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Object Count", None))
        self.lcdNumber_landslide.setStyleSheet(QCoreApplication.translate("MainWindow", u"font: 700 20pt \"Ubuntu\";", None))
        self.lcdNumber_fallentree.setStyleSheet(QCoreApplication.translate("MainWindow", u"font: 700 20pt \"Ubuntu\";", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Fallen Tree", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Road Collapse", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Landslide", None))
        self.lcdNumber_roadcollapse.setStyleSheet(QCoreApplication.translate("MainWindow", u"font: 700 20pt \"Ubuntu\";", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Rock", None))
    # retranslateUi

